#ifndef INSTRUMENTSTOSTRINGEDINSTRUMENTS_BASSGUITAR_H
#define INSTRUMENTSTOSTRINGEDINSTRUMENTS_BASSGUITAR_H

#include "StringedInstrument.h"


class BassGuitar : public StringedInstrument{

};


#endif //INSTRUMENTSTOSTRINGEDINSTRUMENTS_BASSGUITAR_H
